from typing import Any

from app.identity.schemas import IdentityContext, Role
from app.skills.argument_schemas import (
    ArgumentValidationStatus,
    ArgumentValueType,
    ToolArgumentSpec,
)
from app.skills.registry import SkillRegistry, build_default_skill_registry
from app.skills.schemas import (
    ProposalValidationReason,
    ProposalValidationStatus,
    SkillProposal,
    SkillProposalStep,
    SkillSpec,
    SkillStep,
)
from app.skills.validator import ProposalValidator
from app.tools.schemas import RiskLevel


def _identity(scopes: list[str] | None = None) -> IdentityContext:
    return IdentityContext(
        user_id="user-123",
        api_key_id="key-123",
        role=Role.OPERATOR,
        scopes=scopes or ["tools:inspect", "tools:draft", "tools:trigger_workflow"],
    )


def _proposal(
    skill_id: str,
    arguments_by_step_id: dict[str, dict[str, Any]] | None = None,
    registry: SkillRegistry | None = None,
) -> SkillProposal:
    registry = registry or build_default_skill_registry()
    skill = registry.get_skill(skill_id, version="1.0")
    arguments_by_step_id = arguments_by_step_id or {}

    return SkillProposal(
        proposed_skill_id=skill.skill_id,
        proposed_skill_version=skill.version,
        rationale="The user requested a known sandbox skill.",
        steps=[
            SkillProposalStep(
                step_id=step.step_id,
                description=step.description,
                tool_name=step.tool_name,
                allowed_args_schema=step.allowed_args_schema,
                required_scopes=step.required_scopes,
                risk_level=step.risk_level,
                arguments=arguments_by_step_id.get(step.step_id, {}),
            )
            for step in skill.steps
        ],
    )


def _validate(proposal: SkillProposal, registry: SkillRegistry | None = None):
    validator = ProposalValidator(registry or build_default_skill_registry())

    return validator.validate(proposal, _identity())


def _issue_codes(result) -> list[str]:
    assert result.validated_skill_plan is not None

    return [issue.reason_code for issue in result.validated_skill_plan.issues]


def _single_step_registry(argument_specs: list[ToolArgumentSpec]) -> SkillRegistry:
    registry = SkillRegistry()
    registry.register(
        SkillSpec(
            skill_id="inspect_sandbox_health",
            version="1.0",
            name="Inspect sandbox health",
            description="Inspect predictable sandbox issue status data.",
            steps=[
                SkillStep(
                    step_id="inspect_issues",
                    description="Inspect sandbox issues using dry-run data.",
                    tool_name="inspect_sandbox_issues",
                    argument_specs=argument_specs,
                    required_scopes=["tools:inspect"],
                    risk_level=RiskLevel.LOW,
                )
            ],
            required_scopes=["tools:inspect"],
            risk_level=RiskLevel.LOW,
        )
    )

    return registry


def test_valid_inspect_repository_argument_is_accepted() -> None:
    proposal = _proposal(
        "inspect_sandbox_health",
        {"inspect_issues": {"repository": "sandbox/demo-repo"}},
    )

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.ACCEPTED
    assert result.validated_skill_plan is not None
    assert result.validated_skill_plan.status == ArgumentValidationStatus.ACCEPTED
    assert result.validated_skill_plan.issues == []
    assert result.validated_skill_plan.step_arguments[0].arguments == {
        "repository": "sandbox/demo-repo"
    }


def test_valid_draft_arguments_are_accepted() -> None:
    proposal = _proposal(
        "draft_sandbox_issue_comment",
        {
            "draft_comment": {
                "issue_id": 1,
                "comment_body": "Draft response generated by proposer.",
            }
        },
    )

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.ACCEPTED
    assert result.validated_skill_plan is not None
    assert result.validated_skill_plan.step_arguments[0].arguments == {
        "issue_id": 1,
        "comment_body": "Draft response generated by proposer.",
    }


def test_valid_workflow_arguments_are_accepted() -> None:
    proposal = _proposal(
        "simulate_sandbox_workflow",
        {"simulate_workflow": {"workflow_name": "ci.yml", "ref": "main"}},
    )

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.ACCEPTED
    assert result.validated_skill_plan is not None
    assert result.validated_skill_plan.step_arguments[0].arguments == {
        "workflow_name": "ci.yml",
        "ref": "main",
    }


def test_optional_omitted_argument_uses_trusted_default() -> None:
    proposal = _proposal("inspect_sandbox_health")

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.ACCEPTED
    assert result.validated_skill_plan is not None
    assert result.validated_skill_plan.step_arguments[0].arguments == {
        "repository": "sandbox/demo-repo"
    }


def test_optional_omitted_argument_is_allowed_without_default() -> None:
    registry = _single_step_registry(
        [
            ToolArgumentSpec(
                name="repository",
                value_type=ArgumentValueType.STRING,
                required=False,
            )
        ]
    )
    proposal = _proposal("inspect_sandbox_health", registry=registry)

    result = _validate(proposal, registry=registry)

    assert result.status == ProposalValidationStatus.ACCEPTED
    assert result.validated_skill_plan is not None
    assert result.validated_skill_plan.step_arguments[0].arguments == {}


def test_sensitive_argument_name_is_tracked_for_redaction() -> None:
    registry = _single_step_registry(
        [
            ToolArgumentSpec(
                name="repository",
                value_type=ArgumentValueType.STRING,
                sensitive=True,
            )
        ]
    )
    proposal = _proposal(
        "inspect_sandbox_health",
        {"inspect_issues": {"repository": "sandbox/private-repo"}},
        registry=registry,
    )

    result = _validate(proposal, registry=registry)

    assert result.status == ProposalValidationStatus.ACCEPTED
    assert result.validated_skill_plan is not None
    assert result.validated_skill_plan.step_arguments[0].redacted_argument_names == [
        "repository"
    ]


def test_missing_required_argument_is_rejected() -> None:
    proposal = _proposal("draft_sandbox_issue_comment")

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.REJECTED
    assert result.rejection_reasons == [ProposalValidationReason.INVALID_ARGUMENTS]
    assert _issue_codes(result) == ["missing_required_argument", "missing_required_argument"]


def test_unknown_extra_argument_is_rejected() -> None:
    proposal = _proposal(
        "inspect_sandbox_health",
        {"inspect_issues": {"repository": "sandbox/demo-repo", "extra": "value"}},
    )

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.REJECTED
    assert _issue_codes(result) == ["unknown_argument"]


def test_forbidden_control_plane_argument_is_rejected() -> None:
    proposal = _proposal(
        "inspect_sandbox_health",
        {"inspect_issues": {"repository": "sandbox/demo-repo", "identity": "admin"}},
    )

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.REJECTED
    assert _issue_codes(result) == ["forbidden_argument_name"]


def test_wrong_type_is_rejected() -> None:
    proposal = _proposal(
        "inspect_sandbox_health",
        {"inspect_issues": {"repository": 123}},
    )

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.REJECTED
    assert _issue_codes(result) == ["invalid_argument_type"]


def test_bool_is_rejected_for_integer_argument() -> None:
    proposal = _proposal(
        "draft_sandbox_issue_comment",
        {
            "draft_comment": {
                "issue_id": True,
                "comment_body": "Draft response generated by proposer.",
            }
        },
    )

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.REJECTED
    assert _issue_codes(result) == ["invalid_argument_type"]


def test_string_integer_is_not_coerced() -> None:
    proposal = _proposal(
        "draft_sandbox_issue_comment",
        {
            "draft_comment": {
                "issue_id": "1",
                "comment_body": "Draft response generated by proposer.",
            }
        },
    )

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.REJECTED
    assert _issue_codes(result) == ["invalid_argument_type"]


def test_allowed_values_are_enforced() -> None:
    registry = _single_step_registry(
        [
            ToolArgumentSpec(
                name="repository",
                value_type=ArgumentValueType.STRING,
                allowed_values=["sandbox/demo-repo"],
            )
        ]
    )
    proposal = _proposal(
        "inspect_sandbox_health",
        {"inspect_issues": {"repository": "other/repo"}},
        registry=registry,
    )

    result = _validate(proposal, registry=registry)

    assert result.status == ProposalValidationStatus.REJECTED
    assert _issue_codes(result) == ["invalid_allowed_value"]


def test_max_length_is_enforced() -> None:
    registry = _single_step_registry(
        [
            ToolArgumentSpec(
                name="repository",
                value_type=ArgumentValueType.STRING,
                max_length=8,
            )
        ]
    )
    proposal = _proposal(
        "inspect_sandbox_health",
        {"inspect_issues": {"repository": "sandbox/demo-repo"}},
        registry=registry,
    )

    result = _validate(proposal, registry=registry)

    assert result.status == ProposalValidationStatus.REJECTED
    assert _issue_codes(result) == ["string_too_long"]


def test_object_and_list_values_are_rejected() -> None:
    object_proposal = _proposal(
        "inspect_sandbox_health",
        {"inspect_issues": {"repository": {"name": "sandbox/demo-repo"}}},
    )
    list_proposal = _proposal(
        "inspect_sandbox_health",
        {"inspect_issues": {"repository": ["sandbox/demo-repo"]}},
    )

    object_result = _validate(object_proposal)
    list_result = _validate(list_proposal)

    assert object_result.status == ProposalValidationStatus.REJECTED
    assert list_result.status == ProposalValidationStatus.REJECTED
    assert _issue_codes(object_result) == ["invalid_argument_type"]
    assert _issue_codes(list_result) == ["invalid_argument_type"]


def test_invalid_argument_schema_is_rejected() -> None:
    registry = _single_step_registry(
        [
            ToolArgumentSpec(
                name="attempt",
                value_type=ArgumentValueType.INTEGER,
                default=True,
            )
        ]
    )
    proposal = _proposal("inspect_sandbox_health", registry=registry)

    result = _validate(proposal, registry=registry)

    assert result.status == ProposalValidationStatus.REJECTED
    assert _issue_codes(result) == ["invalid_argument_schema"]


def test_invalid_arguments_do_not_produce_partial_acceptance() -> None:
    proposal = _proposal(
        "draft_sandbox_issue_comment",
        {
            "draft_comment": {
                "issue_id": 1,
                "comment_body": ["not", "scalar"],
            }
        },
    )

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.REJECTED
    assert result.validated_skill_plan is not None
    assert result.validated_skill_plan.status == ArgumentValidationStatus.REJECTED
    assert result.validated_skill_plan.step_arguments == []
    assert _issue_codes(result) == ["invalid_argument_type"]


def test_invalid_arguments_never_produce_executable_accepted_plan() -> None:
    proposal = _proposal(
        "inspect_sandbox_health",
        {"inspect_issues": {"identity": "admin"}},
    )

    result = _validate(proposal)

    assert result.status == ProposalValidationStatus.REJECTED
    assert result.rejection_reasons == [ProposalValidationReason.INVALID_ARGUMENTS]
    assert result.validated_skill_plan is not None
    assert result.validated_skill_plan.status == ArgumentValidationStatus.REJECTED
    assert result.validated_skill_plan.step_arguments == []
